## 11.3 예외 종류에 따른 처리
- try 블록에는 다양한 종류의 예외가 발생할 수 있고, 이 경우에는 다중 catch를 사용하면 발생하는 예외에 따라 예외 처리 코드를 다르게
작성할 수 있음.
```java
try {
    ArrayIndexOutOfBoundsException 발생
            
    NumberFormatException 발생
            
} catch(ArrayIndexOutOfBoundsException e) {
    예외 처리1
} catch(NumberFormatException e) {
    예외 처리2
}
```
- catch 블록이 여러 개라 할지라도 catch 블록은 단 하나만 실행됨. ➡️ try 블록에서 동시 다발적으로 예외가 발생하지 않으며, 하나의 예외가 발생하면
즉시 실행을 멈추고 해당 catch 블록으로 이동하기 때문임.

```java
// ❌ 잘못된 예시
try {
    ArrayIndexOutOfBoundsException 발생
            
    NumberFormatException 발생
            
} catch(Exception e) {
    예외 처리1
} catch(ArrayIndexOutOfBoundsException e) { //ArrayIndexOutOfBoundsException 발생 시 실행 안됨.
    예외 처리2
}
```
- 처리해야 할 예외 클래스들이 상속 관계에 있을 때는 `⚠️하위 클래스 catch 블록을 먼저 작성하고 상위 클래스 catch 블록을 나중에 작성⚠️`해야 함.
- 예외가 발생하면 catch 블록은 위에서부터 차례대로 검사 대상이 되는데, 하위 예외도 상위 클래스 타입이므로 상위 클래스 catch 블록이 먼저
검사 대상이 되면 안 됨.

### 🙋 면접 예상 질문
- 다중 catch를 사용할 때 주의해야 할 점에 대해 설명해주세요.